#!/bin/bash

cd "$(dirname "$0")"

function finish {
  [ -d resources ] && rm -r resources
  [ -d resources ] && rm -rf content/docs/
  [ -d resources ] && rm -rf static/docs
  [ -d resources ] && rm -rf data/docs
  [ -d resources ] && rm -rf */__pycache__/
  rmdir * 2> /dev/null
}
trap finish EXIT QUIT ABRT KILL SEGV TERM STOP
finish
[ -d public ] && rm -rf public/*

python3 doxml/dumper.py dox/combined.xml .
docker run "-u$(id -u):$(id -g)" --rm -i -v "$(pwd):/src" klakegg/hugo:0.81.0-ext-alpine-ci
