#!/usr/bin/env bash

cd "$(dirname "$0")"

function do_cleanup {
  rm -rf resources
  rm -rf content/docs/
  rm -rf static/docs
  rm -rf data/docs
  rm -rf */__pycache__/
  rmdir * 2> /dev/null
}
trap do_cleanup EXIT

do_cleanup 2> /dev/null
python3 doxml/dumper.py dox/combined.xml .
docker run -u$(id -u):$(id -g) --rm -v $(pwd):/src klakegg/hugo:0.72.0-ext-alpine $@
