#!/usr/bin/env bash

cd "$(dirname "$0")"



function finish {
  rm -r resources
}
trap finish EXIT

if [ "$#" -eq 0 ]; then
    docker run -u1000:1000 --rm -it -v $(pwd):/src -p 1313:1313 klakegg/hugo:0.61.0-ext-alpine server
else
    docker run -u1000:1000 --rm -it -v $(pwd):/src -p 1313:1313 klakegg/hugo:0.61.0-ext-alpine $@
fi
