# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: Checkout gh-pages
      run: |
        git fetch --all -p
        pwd
        ls -la
        mkdir public
        git remote -v
        git branch -a
        git worktree add -B gh-pages public remotes/origin/gh-pages
        ls -la
    - name: Build site
      run: |
        cd "${GITHUB_WORKSPACE}"
        "${GITHUB_WORKSPACE}/build" -e github
    - name: Push
      run: |
        cd public
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@noreply.example.com"
        git add -A .
        git commit -m "New version deployed by ${GITHUB_EVENT_NAME} ${GITHUB_RUN_NUMBER}"
        git push -f origin gh-pages
